import { TENANT_STATUS_ENUM } from "@catering/types";
import { Tenants } from "@/features/admin/tenants";

export default function TenantsRoute() {
  const now = new Date();

  const tenants = {
    data: [
      {
        id: "tenant-1",
        name: "Dhaka Corporate Meals",
        phone: "01712345678",
        status: TENANT_STATUS_ENUM.ACTIVE,
        description: "Provides daily catering to office teams.",
        headline: "Trusted catering for busy offices",
        contactAddress: "House 12, Road 3, Dhanmondi, Dhaka",
        contactEmail: "dhaka.corporate@example.com",
        contactPhone: "01712345678",
        contactWhatsapp: "01712345678",
        deliveryFee: 60,
        logoUrl: "https://via.placeholder.com/150",
        menuUrl: "https://example.com/menu1",
        socialFacebookUrl: "https://facebook.com/tenant1",
        socialInstagramUrl: "https://instagram.com/tenant1",
        socialYoutubeUrl: "https://youtube.com/tenant1",
        lastOrderDate: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "tenant-2",
        name: "Uttara Lunch Hub",
        phone: "01822345678",
        status: TENANT_STATUS_ENUM.ACTIVE,
        description: "Lunch and bulk meal delivery service.",
        headline: "Fresh lunches every day",
        contactAddress: "Sector 11, Uttara, Dhaka",
        contactEmail: "uttara.lunch@example.com",
        contactPhone: "01822345678",
        contactWhatsapp: "01822345678",
        deliveryFee: 55,
        logoUrl: "https://via.placeholder.com/150",
        menuUrl: "https://example.com/menu2",
        socialFacebookUrl: "https://facebook.com/tenant2",
        socialInstagramUrl: "https://instagram.com/tenant2",
        socialYoutubeUrl: "https://youtube.com/tenant2",
        lastOrderDate: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "tenant-3",
        name: "Banani Catering Group",
        phone: "01933456789",
        status: TENANT_STATUS_ENUM.TERMINATED,
        description: "Legacy contract account that has ended.",
        headline: "Contract completed",
        contactAddress: "Road 10, Banani, Dhaka",
        contactEmail: "banani.catering@example.com",
        contactPhone: "01933456789",
        contactWhatsapp: "01933456789",
        deliveryFee: 70,
        logoUrl: "https://via.placeholder.com/150",
        menuUrl: "https://example.com/menu3",
        socialFacebookUrl: "https://facebook.com/tenant3",
        socialInstagramUrl: "https://instagram.com/tenant3",
        socialYoutubeUrl: "https://youtube.com/tenant3",
        lastOrderDate: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "tenant-4",
        name: "Old Town Events",
        phone: "01644567890",
        status: TENANT_STATUS_ENUM.TERMINATED,
        description: "Stopped operations after event season.",
        headline: "Event season closed",
        contactAddress: "Nazimuddin Road, Old Dhaka",
        contactEmail: "oldtown.events@example.com",
        contactPhone: "01644567890",
        contactWhatsapp: "01644567890",
        deliveryFee: 65,
        logoUrl: "https://via.placeholder.com/150",
        menuUrl: "https://example.com/menu4",
        socialFacebookUrl: "https://facebook.com/tenant4",
        socialInstagramUrl: "https://instagram.com/tenant4",
        socialYoutubeUrl: "https://youtube.com/tenant4",
        lastOrderDate: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "tenant-5",
        name: "Mirpur Family Meals",
        phone: "01555678901",
        status: TENANT_STATUS_ENUM.SUSPENDED,
        description: "Temporarily suspended due to compliance review.",
        headline: "Suspended for review",
        contactAddress: "Mirpur 10, Dhaka",
        contactEmail: "mirpur.family@example.com",
        contactPhone: "01555678901",
        contactWhatsapp: "01555678901",
        deliveryFee: 58,
        logoUrl: "https://via.placeholder.com/150",
        menuUrl: "https://example.com/menu5",
        socialFacebookUrl: "https://facebook.com/tenant5",
        socialInstagramUrl: "https://instagram.com/tenant5",
        socialYoutubeUrl: "https://youtube.com/tenant5",
        lastOrderDate: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "tenant-6",
        name: "Tejgaon Meal Works",
        phone: "01366789012",
        status: TENANT_STATUS_ENUM.SUSPENDED,
        description: "Suspended pending account verification.",
        headline: "Verification in progress",
        contactAddress: "Tejgaon Industrial Area, Dhaka",
        contactEmail: "tejgaon.mealworks@example.com",
        contactPhone: "01366789012",
        contactWhatsapp: "01366789012",
        deliveryFee: 62,
        logoUrl: "https://via.placeholder.com/150",
        menuUrl: "https://example.com/menu6",
        socialFacebookUrl: "https://facebook.com/tenant6",
        socialInstagramUrl: "https://instagram.com/tenant6",
        socialYoutubeUrl: "https://youtube.com/tenant6",
        lastOrderDate: now,
        createdAt: now,
        updatedAt: now,
      },
    ],
    meta: {
      pagination: {
        totalDocs: 6,
        limit: 10,
        hasPrevPage: false,
        hasNextPage: false,
        page: 1,
        totalPages: 1,
        prevPage: null,
        nextPage: null,
        pagingCounter: 1,
      },
    },
  };

  return <Tenants data={tenants} />;
}
